name: release
on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  build:
    name: Build distribution
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    environment:
      name: ${{ github.ref_name }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Update pip
        run: pip install --upgrade pip
      - name: Run pre-commit
        run: |
          pip install pre-commit
          pre-commit run --all
      - name: Build distribution
        run: |
          python -m pip install build
          python -m build
      - name: Store distribution
        uses: actions/upload-artifact@v4
        with:
          name: python-package-distributions
          path: dist/
  publish-to-pypi:
    name: Publish distribution to PyPI
    runs-on: ubuntu-latest
    needs:
      - build
    permissions:
      id-token: write
    environment:
      name: pypi
      url: https://test.pypi.org/p/pyspark-regression
    steps:
      - name: Download all the dists
        uses: actions/download-artifact@v4
        with:
          name: python-package-distributions
          path: dist/
      - name: Publish distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
  github-release:
    name: Sign Python distribution with Sigstore and upload to GitHub Release
    runs-on: ubuntu-latest
    needs:
      - publish-to-pypi
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Download distribution
        uses: actions/download-artifact@v4
        with:
          name: python-package-distributions
          path: dist/
      - name: Sign distribution with Sigstore
        uses: sigstore/gh-action-sigstore-python@v3.0.0
        with:
          inputs: >-
            ./dist/*.tar.gz
            ./dist/*.whl
      - name: Create GitHub Release
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: gh release create "$GITHUB_REF_NAME" --repo "$GITHUB_REPOSITORY" --notes ""
      - name: Upload artifact signatures to GitHub Release
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: gh release upload "$GITHUB_REF_NAME" dist/** --repo "$GITHUB_REPOSITORY"
